import { defaultEditorSettings, defaultTraceOptions, defaultVectorOptions } from '../defaults';

export type OptionHelpSection = 'editing' | 'vectorization';

export interface OptionHelp {
  id: string;
  path: string;
  section: OptionHelpSection;
  group: string;
  label: string;
  explanation: string;
  technicalEffect: string;
  defaultValue: string;
  validValues: string;
  recommendedValues: string;
  warnings: string[];
}

export interface HelpRecipe {
  title: string;
  goal: string;
  settings: string[];
  watchFor: string;
}

const bool = (value: boolean): string => value ? 'On' : 'Off';
const percent = (value: number): string => `${value}%`;
const pixels = (value: number): string => `${value}px`;
const color = (value: string): string => value.toUpperCase();

export const optionHelp: OptionHelp[] = [
  {
    id: 'editor.loadVector',
    path: 'editing.loadVector',
    section: 'editing',
    group: 'Load Vector',
    label: 'Load vector',
    explanation: 'Loads an SVG for editable color and stroke changes. PDFs and raster files can be opened here, but they are placed inside an SVG wrapper instead of being converted to editable paths.',
    technicalEffect: 'SVG files are read as text and passed to the editor pipeline. Non-SVG files are rasterized with the image loader and wrapped in an SVG image element.',
    defaultValue: 'No file loaded',
    validValues: 'SVG, PDF, and SVG MIME uploads accepted by the Editing drop zone.',
    recommendedValues: 'Use SVG when you want real editable paths. Use Vectorization first when you need paths from PNG, JPG, WebP, BMP, GIF, SVG, or PDF artwork.',
    warnings: ['PDF/raster uploads in Editing are image wrappers, so palette replacement and stroke editing cannot reach individual painted shapes.']
  },
  {
    id: 'editor.strokeScale',
    path: 'editor.strokeScale',
    section: 'editing',
    group: 'Stroke',
    label: 'Stroke scale',
    explanation: 'Multiplies existing SVG stroke widths.',
    technicalEffect: 'Every editable stroke width is multiplied by this factor before the SVG preview/export is produced.',
    defaultValue: String(defaultEditorSettings.strokeScale),
    validValues: '0 to 8',
    recommendedValues: 'Use 1 to keep strokes unchanged, 0 to remove strokes, 0.8-1.4 for small cleanup, and higher values for deliberate boldening.',
    warnings: ['Large values can make strokes cover fills or close small holes.']
  },
  {
    id: 'editor.strokeOffset',
    path: 'editor.strokeOffset',
    section: 'editing',
    group: 'Stroke',
    label: 'Stroke offset',
    explanation: 'Adds or subtracts a fixed number of pixels after stroke scaling.',
    technicalEffect: 'After stroke scale is applied, this pixel offset is added to each editable stroke width and clamped so widths do not become negative.',
    defaultValue: pixels(defaultEditorSettings.strokeOffset),
    validValues: '-12px to 24px',
    recommendedValues: 'Use 0 for no change, small positive offsets for stronger lineart, and small negative offsets for lighter strokes.',
    warnings: ['Negative offsets can remove thin strokes entirely.']
  },
  {
    id: 'editor.model',
    path: 'editor.model',
    section: 'editing',
    group: 'Color',
    label: 'Color model',
    explanation: 'Chooses whether color edits are calculated with HSL lightness or HSV value.',
    technicalEffect: 'HSL uses hue, saturation, and lightness channels. HSV uses hue, saturation, and value channels while leaving the inactive lightness/value control unused.',
    defaultValue: defaultEditorSettings.model.toUpperCase(),
    validValues: 'HSL or HSV',
    recommendedValues: 'Use HSL for illustration-style lightening and darkening. Use HSV when you want brightness changes that feel closer to a color picker.',
    warnings: ['Switching models changes how brightness adjustments feel, even if hue and saturation stay the same.']
  },
  {
    id: 'editor.protectWhite',
    path: 'editor.protectWhite',
    section: 'editing',
    group: 'Color',
    label: 'Protect whites',
    explanation: 'Keeps white and near-white colors from being shifted by global color edits.',
    technicalEffect: 'Near-white fills and strokes are skipped by hue, saturation, lightness/value, and opacity transforms.',
    defaultValue: bool(defaultEditorSettings.protectWhite),
    validValues: 'On or off',
    recommendedValues: 'Keep on for paper, highlights, and transparent-looking white areas.',
    warnings: ['Turn it off only when white artwork should change color with everything else.']
  },
  {
    id: 'editor.protectBlack',
    path: 'editor.protectBlack',
    section: 'editing',
    group: 'Color',
    label: 'Protect blacks',
    explanation: 'Keeps black and near-black colors from being shifted by global color edits.',
    technicalEffect: 'Near-black fills and strokes are skipped by hue, saturation, lightness/value, and opacity transforms.',
    defaultValue: bool(defaultEditorSettings.protectBlack),
    validValues: 'On or off',
    recommendedValues: 'Turn on when ink or lettering must stay neutral black while colors change.',
    warnings: ['Leaving it off lets black lineart tint with hue and saturation changes.']
  },
  {
    id: 'editor.protectGray',
    path: 'editor.protectGray',
    section: 'editing',
    group: 'Color',
    label: 'Protect grays',
    explanation: 'Keeps low-saturation grays from being tinted by global color edits.',
    technicalEffect: 'Gray fills and strokes are skipped by hue, saturation, lightness/value, and opacity transforms.',
    defaultValue: bool(defaultEditorSettings.protectGray),
    validValues: 'On or off',
    recommendedValues: 'Keep on for pencil, neutral shadows, and scanned gray details.',
    warnings: ['Turn it off if gray artwork should receive the same color cast as the rest of the SVG.']
  },
  {
    id: 'editor.hue',
    path: 'editor.hue',
    section: 'editing',
    group: 'Color',
    label: 'Hue',
    explanation: 'Rotates editable colors around the color wheel.',
    technicalEffect: 'Adds the selected degrees to each editable color hue in the active HSL or HSV model.',
    defaultValue: `${defaultEditorSettings.hue}deg`,
    validValues: '-180deg to 180deg',
    recommendedValues: 'Use small changes such as -20deg to 20deg for natural palette shifts, or larger values for a new palette.',
    warnings: ['Protected white, black, and gray colors are skipped when their protection toggles are on.']
  },
  {
    id: 'editor.saturation',
    path: 'editor.saturation',
    section: 'editing',
    group: 'Color',
    label: 'Saturation',
    explanation: 'Increases or decreases color intensity.',
    technicalEffect: 'Adds the percentage to the saturation channel of editable colors and clamps the result to the valid color range.',
    defaultValue: percent(defaultEditorSettings.saturation),
    validValues: '-100% to 200%',
    recommendedValues: 'Use -10% to 30% for subtle cleanup, -100% for grayscale, and high positive values for posterized intensity.',
    warnings: ['High saturation can exaggerate compression noise or color quantization artifacts.']
  },
  {
    id: 'editor.lightness',
    path: 'editor.lightness',
    section: 'editing',
    group: 'Color',
    label: 'Lightness',
    explanation: 'Lightens or darkens colors when the color model is HSL.',
    technicalEffect: 'Adds the percentage to the HSL lightness channel of editable colors.',
    defaultValue: percent(defaultEditorSettings.lightness),
    validValues: '-100% to 100%',
    recommendedValues: 'Use small positive values to brighten scans, and small negative values to add weight.',
    warnings: ['Extreme values can flatten detail into pure white or black.']
  },
  {
    id: 'editor.value',
    path: 'editor.value',
    section: 'editing',
    group: 'Color',
    label: 'Value',
    explanation: 'Brightens or darkens colors when the color model is HSV.',
    technicalEffect: 'Adds the percentage to the HSV value channel of editable colors.',
    defaultValue: percent(defaultEditorSettings.value),
    validValues: '-100% to 100%',
    recommendedValues: 'Use HSV value for color-picker-like brightness edits, especially on saturated colors.',
    warnings: ['Extreme values can clip highlights or crush shadows.']
  },
  {
    id: 'editor.opacity',
    path: 'editor.opacity',
    section: 'editing',
    group: 'Color',
    label: 'Opacity',
    explanation: 'Scales the opacity of editable fills and strokes.',
    technicalEffect: 'Multiplies existing opacity by this value while preserving the SVG structure.',
    defaultValue: String(defaultEditorSettings.opacity),
    validValues: '0 to 1',
    recommendedValues: 'Use 1 for unchanged opacity, 0.5 for half opacity, and 0 to make editable colors transparent.',
    warnings: ['Lowering opacity can reveal hidden overlaps or background rectangles.']
  },
  {
    id: 'editor.palette.enabled',
    path: 'editor.selectedColors[color]',
    section: 'editing',
    group: 'Palette',
    label: 'Palette enable/disable',
    explanation: 'Controls whether a detected SVG palette color participates in editing and export.',
    technicalEffect: 'Each palette checkbox stores a per-color boolean. Unchecked colors are skipped by global edits and replacement.',
    defaultValue: 'Enabled for every detected color',
    validValues: 'On or off for each detected hex color.',
    recommendedValues: 'Disable colors that must remain untouched, such as brand colors or registration marks.',
    warnings: ['Palette rows only appear for colors detected in the loaded SVG. Wrapped raster images do not expose individual palette colors.']
  },
  {
    id: 'editor.palette.replacement',
    path: 'editor.replacements[color]',
    section: 'editing',
    group: 'Palette',
    label: 'Palette replacement color',
    explanation: 'Replaces one detected SVG palette color with a chosen color.',
    technicalEffect: 'Stores a per-color hex replacement and rewrites matching editable fills/strokes during SVG edit application.',
    defaultValue: 'Original detected color',
    validValues: 'Any color available from the browser color picker, stored as hex.',
    recommendedValues: 'Use for precise spot-color swaps after broad HSL/HSV adjustments.',
    warnings: ['Only exact detected colors are replaced; gradients, images, and colors not parsed into the palette may not change.']
  },
  {
    id: 'editor.exportSvg',
    path: 'editing.exportSvg',
    section: 'editing',
    group: 'Export',
    label: 'Export SVG',
    explanation: 'Downloads the current edited SVG.',
    technicalEffect: 'Serializes the edited SVG string and downloads it as edited-vector.svg.',
    defaultValue: 'Action; disabled until an editable SVG is available',
    validValues: 'Button action',
    recommendedValues: 'Use when you need scalable paths for Illustrator, Figma, web, or later editing.',
    warnings: ['If the source was a wrapped raster/PDF, the exported SVG may still contain an embedded image.']
  },
  {
    id: 'editor.exportPng',
    path: 'editing.exportPng',
    section: 'editing',
    group: 'Export',
    label: 'Export PNG',
    explanation: 'Downloads a raster PNG of the current edited SVG.',
    technicalEffect: 'Rasterizes the current SVG in the browser and downloads a 2x PNG.',
    defaultValue: 'Action; disabled until an editable SVG is available',
    validValues: 'Button action',
    recommendedValues: 'Use when you need a bitmap preview or upload format.',
    warnings: ['PNG export is no longer editable as paths, and very large SVGs may take longer to rasterize.']
  },
  {
    id: 'vector.loadBitmap',
    path: 'vectorization.loadBitmap',
    section: 'vectorization',
    group: 'Load Bitmap',
    label: 'Load bitmap',
    explanation: 'Loads artwork for vectorization into editable SVG paths.',
    technicalEffect: 'Raster, SVG, and PDF inputs are decoded or rasterized into ImageData before tracing.',
    defaultValue: 'No source loaded',
    validValues: 'PNG, JPG, JPEG, WebP, BMP, GIF, SVG, and PDF files accepted by the Vectorization drop zone.',
    recommendedValues: 'Use the highest-quality scan or image you have, then control working size with Max side.',
    warnings: ['SVG and PDF inputs are rasterized first in Vectorization, so the output is newly traced paths rather than the original SVG/PDF structure.']
  },
  {
    id: 'filters.search',
    path: 'filters.search',
    section: 'vectorization',
    group: 'Filter Library',
    label: 'Search filters',
    explanation: 'Filters the built-in and custom vectorization presets by text.',
    technicalEffect: 'Matches the search text against filter id, name, description, recommended use, mode, categories, and tags.',
    defaultValue: 'Empty search',
    validValues: 'Any search text',
    recommendedValues: 'Search by task words such as watercolor, lineart, lightweight, detail, balanced, or mode names.',
    warnings: ['Search only changes which filters are shown; it does not change vectorization settings until a filter is applied.']
  },
  {
    id: 'filters.category',
    path: 'filters.category',
    section: 'vectorization',
    group: 'Filter Library',
    label: 'Filter category',
    explanation: 'Narrows the Filter Library list to one category.',
    technicalEffect: 'Only filters whose metadata includes the selected category remain visible.',
    defaultValue: 'All',
    validValues: 'All plus categories supplied by built-in and custom filters.',
    recommendedValues: 'Use Watercolor, Lineart, Lightweight SVG, Balanced, Maximum detail, or Custom to quickly narrow the list.',
    warnings: ['Category chips combine with search text, so an empty result may mean both filters are active.']
  },
  {
    id: 'filters.apply',
    path: 'filters.apply',
    section: 'vectorization',
    group: 'Filter Library',
    label: 'Apply filter',
    explanation: 'Copies a filter preset into the current vectorization controls.',
    technicalEffect: 'Merges the selected partial or custom VectorOptions object into the active settings and marks that filter as applied.',
    defaultValue: 'Action; available for each visible filter',
    validValues: 'Button action',
    recommendedValues: 'Apply a preset as a starting point, then tune individual controls for the current image.',
    warnings: ['Applying a filter overwrites current vectorization settings, but controls remain editable afterward.']
  },
  {
    id: 'filters.saveCurrent',
    path: 'filters.saveCurrent',
    section: 'vectorization',
    group: 'Filter Library',
    label: 'Save current settings as filter',
    explanation: 'Stores the current vectorization settings as a reusable custom filter.',
    technicalEffect: 'Clones the current VectorOptions and saves it in browser localStorage with the supplied name and description.',
    defaultValue: 'Save form closed',
    validValues: 'Name up to 80 characters; description up to 240 characters.',
    recommendedValues: 'Save settings after tuning a source type you expect to process again.',
    warnings: ['Custom filters are local to the current browser/profile unless exported as JSON.']
  },
  {
    id: 'filters.exportCustom',
    path: 'filters.exportCustom',
    section: 'vectorization',
    group: 'Filter Library',
    label: 'Export custom filters',
    explanation: 'Downloads custom filters as JSON.',
    technicalEffect: 'Serializes custom filter metadata and VectorOptions into a versioned JSON file.',
    defaultValue: 'Action; disabled until a custom filter exists',
    validValues: 'Button action',
    recommendedValues: 'Export before switching browsers or sharing a tuned setup with someone else.',
    warnings: ['Built-in filters are not included because they already ship with the app.']
  },
  {
    id: 'filters.importJson',
    path: 'filters.importJson',
    section: 'vectorization',
    group: 'Filter Library',
    label: 'Import JSON',
    explanation: 'Imports custom filters from a JSON file.',
    technicalEffect: 'Parses one filter, an array of filters, or a versioned export object and validates each VectorOptions payload before saving.',
    defaultValue: 'No import selected',
    validValues: 'JSON files exported by Vector Lab Studio or matching the custom filter schema.',
    recommendedValues: 'Use with filters exported from the same app version whenever possible.',
    warnings: ['Invalid filters are rejected. Imported filters with duplicate ids receive new ids.']
  },
  {
    id: 'filters.rename',
    path: 'filters.rename',
    section: 'vectorization',
    group: 'Filter Library',
    label: 'Rename custom filter',
    explanation: 'Edits the name and description of a saved custom filter.',
    technicalEffect: 'Updates the custom filter metadata in localStorage without changing its saved VectorOptions.',
    defaultValue: 'Action; custom filters only',
    validValues: 'Name up to 80 characters; description up to 240 characters.',
    recommendedValues: 'Use descriptive names based on source type or project.',
    warnings: ['Renaming does not update the settings stored inside the filter.']
  },
  {
    id: 'filters.delete',
    path: 'filters.delete',
    section: 'vectorization',
    group: 'Filter Library',
    label: 'Delete custom filter',
    explanation: 'Removes a saved custom filter from the current browser.',
    technicalEffect: 'Deletes the custom filter entry from localStorage after confirmation.',
    defaultValue: 'Action; custom filters only',
    validValues: 'Button action',
    recommendedValues: 'Export filters you may need later before deleting them.',
    warnings: ['Deletion cannot be undone unless you have an exported JSON copy.']
  },
  {
    id: 'vector.mode',
    path: 'vector.mode',
    section: 'vectorization',
    group: 'Method',
    label: 'Mode',
    explanation: 'Chooses the vectorization strategy.',
    technicalEffect: 'Layered creates a color layer and a lineart layer. Color traces quantized color shapes only. Binary traces a thresholded ink mask only.',
    defaultValue: defaultVectorOptions.mode,
    validValues: 'layered, color, or binary',
    recommendedValues: 'Use layered for watercolor with ink, color for flat color SVGs, and binary for clean black lineart.',
    warnings: ['Layered output is richer but usually larger and slower than color or binary output.']
  },
  {
    id: 'vector.maxSide',
    path: 'vector.maxSide',
    section: 'vectorization',
    group: 'Method',
    label: 'Max side',
    explanation: 'Sets the largest working dimension used for vectorization.',
    technicalEffect: 'The source image is resized so its longest side is no larger than this value before tracing.',
    defaultValue: pixels(defaultVectorOptions.maxSide),
    validValues: '240px to 3200px',
    recommendedValues: 'Use 1100-1500px for compact SVGs, 1800-2400px for balanced detail, and 2600-3200px for maximum detail.',
    warnings: ['Large values create more pixels to analyze, which can make vectorization slower and SVGs heavier.']
  },
  {
    id: 'vector.blur',
    path: 'vector.blur',
    section: 'vectorization',
    group: 'Method',
    label: 'Pre-blur',
    explanation: 'Applies a shared blur before tracing to reduce noise.',
    technicalEffect: 'Updates the shared vector blur and also synchronizes the color and binary layer blur values.',
    defaultValue: pixels(defaultVectorOptions.blur),
    validValues: '0px to 4px',
    recommendedValues: 'Use 0-0.15px for crisp lineart, 0.3-0.7px for watercolor grain, and higher values for noisy photos.',
    warnings: ['Too much blur can erase small details or merge nearby shapes.']
  },
  {
    id: 'vector.livePreview',
    path: 'vector.livePreview',
    section: 'vectorization',
    group: 'Method',
    label: 'Live preview',
    explanation: 'Automatically re-runs vectorization after settings change.',
    technicalEffect: 'When enabled, the app debounces setting changes and starts a preview vectorization after a short delay.',
    defaultValue: bool(defaultVectorOptions.livePreview),
    validValues: 'On or off',
    recommendedValues: 'Use on for small images and quick tuning; use off for high-resolution scans or expensive layered settings.',
    warnings: ['Live preview can feel slow when Max side, Colors, Iterations, or Max samples are high.']
  },
  {
    id: 'output.openInEditor',
    path: 'output.openInEditor',
    section: 'vectorization',
    group: 'Method',
    label: 'Open result in Editing',
    explanation: 'Automatically opens a manually vectorized result in the Editing tab.',
    technicalEffect: 'After a manual Vectorize run succeeds, the generated SVG is copied into editor state and the active tab changes to Editing.',
    defaultValue: bool(defaultVectorOptions.output.openInEditor),
    validValues: 'On or off',
    recommendedValues: 'Turn on when your next step is color/stroke editing. Leave off when comparing vectorization settings.',
    warnings: ['Live preview results do not automatically switch tabs.']
  },
  {
    id: 'background.enabled',
    path: 'background.enabled',
    section: 'vectorization',
    group: 'Background',
    label: 'Remove paper/background',
    explanation: 'Controls whether the paper/background mask is used before tracing.',
    technicalEffect: 'When enabled, background pixels are excluded from foreground tracing according to the selected background method.',
    defaultValue: bool(defaultVectorOptions.background.enabled),
    validValues: 'On or off',
    recommendedValues: 'Keep on for scanned paper and artwork on light backgrounds. Turn off for transparent art or images where the background should stay.',
    warnings: ['Over-aggressive removal can delete pale artwork, especially if it touches the image edge.']
  },
  {
    id: 'background.method',
    path: 'background.method',
    section: 'vectorization',
    group: 'Background',
    label: 'Background method',
    explanation: 'Chooses how paper/background pixels are identified.',
    technicalEffect: 'Edge-connected flood-fills paper-like pixels connected to the border. Global-light removes all matching light pixels. None skips paper masking.',
    defaultValue: defaultVectorOptions.background.method,
    validValues: 'edge-connected, global-light, or none',
    recommendedValues: 'Use edge-connected for scans, global-light for evenly lit backgrounds with no white artwork, and none for already transparent or prepared art.',
    warnings: ['Global-light can remove intentional white artwork inside the image.']
  },
  {
    id: 'background.tolerance',
    path: 'background.tolerance',
    section: 'vectorization',
    group: 'Background',
    label: 'Paper tolerance',
    explanation: 'Controls how different a pixel can be from sampled paper and still count as background.',
    technicalEffect: 'Increases or decreases the OKLab color-distance threshold used by the paper mask.',
    defaultValue: percent(defaultVectorOptions.background.tolerance),
    validValues: '1% to 35%',
    recommendedValues: 'Use 6-12% for clean paper, 12-18% for textured watercolor paper, and lower values when pale art is being removed.',
    warnings: ['High tolerance can eat light washes and highlights. Low tolerance can leave paper speckles.']
  },
  {
    id: 'background.minLightness',
    path: 'background.minLightness',
    section: 'vectorization',
    group: 'Background',
    label: 'Min paper lightness',
    explanation: 'Sets the minimum lightness a pixel needs before it can be considered paper.',
    technicalEffect: 'Pixels darker than this lightness percentage are kept as foreground even if they resemble the sampled paper color.',
    defaultValue: percent(defaultVectorOptions.background.minLightness),
    validValues: '40% to 98%',
    recommendedValues: 'Use 72-84% for most scans. Raise it to protect pale color; lower it when beige or gray paper remains.',
    warnings: ['Too low can remove shadows and pale paint. Too high can leave paper around the art.']
  },
  {
    id: 'background.sampleInset',
    path: 'background.sampleInset',
    section: 'vectorization',
    group: 'Background',
    label: 'Sample inset',
    explanation: 'Controls how far in from the edge the paper sampler looks.',
    technicalEffect: 'The paper estimate samples border/corner pixels inset by this many pixels from the image edge.',
    defaultValue: pixels(defaultVectorOptions.background.sampleInset),
    validValues: '2px to 60px',
    recommendedValues: 'Use 10-25px for normal scans, and larger values if scanner edges or shadows contaminate the border.',
    warnings: ['If artwork reaches the sampled border area, the paper estimate can become biased toward art colors.']
  },
  {
    id: 'background.showMask',
    path: 'background.showMask',
    section: 'vectorization',
    group: 'Background',
    label: 'Preview foreground mask',
    explanation: 'Shows the foreground mask instead of normal vector output.',
    technicalEffect: 'The vectorizer returns a mask preview so you can inspect what will be traced as foreground.',
    defaultValue: bool(defaultVectorOptions.background.showMask),
    validValues: 'On or off',
    recommendedValues: 'Use temporarily while tuning background removal, then turn off before final export.',
    warnings: ['Mask preview is a diagnostic view, not the final artwork appearance.']
  },
  {
    id: 'color.quantizer',
    path: 'color.quantizer',
    section: 'vectorization',
    group: 'Color',
    label: 'Quantizer',
    explanation: 'Chooses the color clustering algorithm for color layers.',
    technicalEffect: 'OKLab k-means++ clusters colors in a perceptual color space. RGB median cut recursively divides RGB space into representative buckets.',
    defaultValue: defaultVectorOptions.color.quantizer,
    validValues: 'oklab-kmeans or rgb-median-cut',
    recommendedValues: 'Use OKLab k-means++ for artwork and watercolor. Use RGB median cut for faster, simpler flat-color results.',
    warnings: ['OKLab k-means++ can be slower, especially with high Colors, Iterations, and Max samples.']
  },
  {
    id: 'color.colors',
    path: 'color.colors',
    section: 'vectorization',
    group: 'Color',
    label: 'Colors',
    explanation: 'Sets the maximum number of palette colors used in color tracing.',
    technicalEffect: 'The quantizer reduces sampled foreground pixels to this many representative colors before contours are traced.',
    defaultValue: String(defaultVectorOptions.color.colors),
    validValues: '2 to 96',
    recommendedValues: 'Use 8-18 for lightweight SVGs, 20-36 for balanced watercolor, and 48-96 for preserving subtle washes.',
    warnings: ['More colors usually means more paths, larger files, and longer processing.']
  },
  {
    id: 'color.iterations',
    path: 'color.iterations',
    section: 'vectorization',
    group: 'Color',
    label: 'Iterations',
    explanation: 'Controls how long k-means color clustering refines its palette.',
    technicalEffect: 'For OKLab k-means++, this is the maximum number of centroid update passes. Median cut does not benefit in the same way.',
    defaultValue: String(defaultVectorOptions.color.iterations),
    validValues: '2 to 60',
    recommendedValues: 'Use 12-24 for most work and 30-45 for high-detail watercolor.',
    warnings: ['Higher values can improve palette stability but cost time.']
  },
  {
    id: 'color.sampleLimit',
    path: 'color.sampleLimit',
    section: 'vectorization',
    group: 'Color',
    label: 'Max samples',
    explanation: 'Limits how many foreground pixels are used to learn the color palette.',
    technicalEffect: 'The color quantizer samples up to this many pixels before clustering.',
    defaultValue: defaultVectorOptions.color.sampleLimit.toLocaleString('en-US'),
    validValues: '5,000 to 500,000',
    recommendedValues: 'Use 50,000-140,000 for speed and 250,000-360,000 for large, subtle artwork.',
    warnings: ['Very high sample counts can slow vectorization without visible improvement on simple images.']
  },
  {
    id: 'color.excludeLineart',
    path: 'color.excludeLineart',
    section: 'vectorization',
    group: 'Color',
    label: 'Exclude lineart from color layer',
    explanation: 'Keeps detected ink out of the color layer in layered mode.',
    technicalEffect: 'Pixels darker than Lineart darkness are removed from color quantization/tracing so the lineart layer owns them.',
    defaultValue: bool(defaultVectorOptions.color.excludeLineart),
    validValues: 'On or off',
    recommendedValues: 'Keep on for clean ink over color. Turn off when you want color to underpaint beneath ink and reduce gaps.',
    warnings: ['Turning it on can create white gaps under thick or imperfectly aligned lineart.']
  },
  {
    id: 'color.lineartDarkness',
    path: 'color.lineartDarkness',
    section: 'vectorization',
    group: 'Color',
    label: 'Lineart darkness',
    explanation: 'Defines how dark a pixel must be before it is treated as lineart for layered color separation.',
    technicalEffect: 'Dark pixels below this brightness threshold are considered lineart candidates when excluding ink from the color layer.',
    defaultValue: String(defaultVectorOptions.color.lineartDarkness),
    validValues: '40 to 230',
    recommendedValues: 'Use 130-170 for typical ink. Lower values protect dark paint; higher values catch faint pencil or gray ink.',
    warnings: ['High values can classify shadows or saturated paint as ink and create black blobs.']
  },
  {
    id: 'binary.thresholdMode',
    path: 'line.mode',
    section: 'vectorization',
    group: 'Lineart',
    label: 'Threshold mode',
    explanation: 'Chooses how the lineart mask decides which pixels are ink.',
    technicalEffect: 'Manual uses the Threshold slider. Otsu computes one global threshold. Sauvola computes a local adaptive threshold using the window and k controls.',
    defaultValue: defaultVectorOptions.binary.thresholdMode,
    validValues: 'manual, otsu, or sauvola',
    recommendedValues: 'Use manual for predictable scans, Otsu for quick automatic lineart, and Sauvola for uneven lighting or paper texture.',
    warnings: ['Automatic modes can change substantially between images; manual is often easier to tune precisely.']
  },
  {
    id: 'binary.threshold',
    path: 'line.threshold',
    section: 'vectorization',
    group: 'Lineart',
    label: 'Threshold',
    explanation: 'Sets the manual cutoff between ink and non-ink.',
    technicalEffect: 'When threshold mode is manual, pixels darker than this value are included in the lineart mask before chroma guarding and inversion.',
    defaultValue: String(defaultVectorOptions.binary.threshold),
    validValues: '0 to 255',
    recommendedValues: 'Use 145-190 for typical black ink scans. Raise it to catch lighter marks; lower it to reject shadows.',
    warnings: ['High thresholds can turn dark paint and shadows into lineart.']
  },
  {
    id: 'binary.sauvolaWindow',
    path: 'line.sauvolaWindow',
    section: 'vectorization',
    group: 'Lineart',
    label: 'Sauvola window',
    explanation: 'Sets the local neighborhood size for Sauvola adaptive thresholding.',
    technicalEffect: 'Sauvola computes local statistics inside this odd-sized pixel window to classify ink.',
    defaultValue: pixels(defaultVectorOptions.binary.sauvolaWindow),
    validValues: '9px to 101px, step 2',
    recommendedValues: 'Use 25-45px for most lineart and larger windows for broad, uneven lighting.',
    warnings: ['Small windows can amplify paper texture. Large windows can miss local faint marks.']
  },
  {
    id: 'binary.sauvolaK',
    path: 'line.sauvolaK',
    section: 'vectorization',
    group: 'Lineart',
    label: 'Sauvola k',
    explanation: 'Controls Sauvola threshold sensitivity.',
    technicalEffect: 'Adjusts the adaptive threshold formula used in Sauvola mode.',
    defaultValue: String(defaultVectorOptions.binary.sauvolaK),
    validValues: '0.05 to 0.8',
    recommendedValues: 'Use 0.2-0.35 for most scans. Increase if faint ink is missing; decrease if texture becomes ink.',
    warnings: ['High k values can pull paper grain and stains into the lineart mask.']
  },
  {
    id: 'binary.maxChroma',
    path: 'line.maxChroma',
    section: 'vectorization',
    group: 'Lineart',
    label: 'Ink chroma guard',
    explanation: 'Rejects saturated color pixels from the lineart mask.',
    technicalEffect: 'Only pixels with chroma at or below this value can become ink. 255 effectively disables the guard.',
    defaultValue: String(defaultVectorOptions.binary.maxChroma),
    validValues: '0 to 255',
    recommendedValues: 'Use 50-90 for watercolor with black ink and 255 for pure grayscale lineart.',
    warnings: ['Too low can remove colored ink or warm black lines. Too high can turn dark saturated paint into lineart.']
  },
  {
    id: 'binary.invert',
    path: 'line.invert',
    section: 'vectorization',
    group: 'Lineart',
    label: 'Invert',
    explanation: 'Swaps which side of the threshold becomes lineart.',
    technicalEffect: 'Inverts the binary lineart mask after thresholding logic.',
    defaultValue: bool(defaultVectorOptions.binary.invert),
    validValues: 'On or off',
    recommendedValues: 'Use off for dark ink on light paper. Turn on for light marks on a dark background.',
    warnings: ['Inverting normal scans usually fills the background instead of the drawing.']
  },
  {
    id: 'binary.fill',
    path: 'line.fill',
    section: 'vectorization',
    group: 'Lineart',
    label: 'Line color',
    explanation: 'Sets the fill color used for traced lineart paths.',
    technicalEffect: 'The binary/lineart SVG paths are emitted with this fill color.',
    defaultValue: color(defaultVectorOptions.binary.fill),
    validValues: 'Any color available from the browser color picker, stored as hex.',
    recommendedValues: 'Use near-black for ink, or a brand/accent color for single-color graphics.',
    warnings: ['This affects generated lineart only; existing SVG colors are edited in the Editing tab.']
  },
  {
    id: 'trace.minArea',
    path: 'trace.minArea',
    section: 'vectorization',
    group: 'Contours',
    label: 'Contour minimum area',
    explanation: 'Removes tiny traced islands.',
    technicalEffect: 'Contours with an area below this pixel threshold are discarded before SVG paths are emitted.',
    defaultValue: `${defaultTraceOptions.minArea}px2`,
    validValues: '0px2 to 500px2',
    recommendedValues: 'Use 0-5 for maximum detail, 8-25 for cleanup, and higher values for lightweight output.',
    warnings: ['High values can delete small dots, punctuation, texture, and fine hatching.']
  },
  {
    id: 'trace.simplify',
    path: 'trace.simplify',
    section: 'vectorization',
    group: 'Contours',
    label: 'RDP simplification',
    explanation: 'Straightens traced outlines by removing unnecessary points.',
    technicalEffect: 'Applies Ramer-Douglas-Peucker simplification using this pixel tolerance.',
    defaultValue: pixels(defaultTraceOptions.simplify),
    validValues: '0px to 8px',
    recommendedValues: 'Use 0.2-0.7 for detailed art, 0.8-1.5 for balanced output, and 2+ for very small SVGs.',
    warnings: ['High simplification can distort curves, corners, lettering, and small shapes.']
  },
  {
    id: 'trace.smooth',
    path: 'trace.smooth',
    section: 'vectorization',
    group: 'Contours',
    label: 'Curve smoothing',
    explanation: 'Rounds traced contours into smoother curves.',
    technicalEffect: 'Converts simplified polygon segments toward cubic curve output according to this percentage.',
    defaultValue: percent(defaultTraceOptions.smooth),
    validValues: '0% to 100%',
    recommendedValues: 'Use 0-15% for lineart, 5-25% for balanced tracing, and higher values for soft organic fills.',
    warnings: ['Too much smoothing can round off deliberate corners and fine detail.']
  },
  {
    id: 'trace.precision',
    path: 'trace.precision',
    section: 'vectorization',
    group: 'Contours',
    label: 'Precision',
    explanation: 'Controls how many decimal places SVG path coordinates keep.',
    technicalEffect: 'Rounds emitted path coordinates to this many decimal places.',
    defaultValue: String(defaultTraceOptions.precision),
    validValues: '0 to 4',
    recommendedValues: 'Use 1-2 for most output, 0 for compact files, and 3-4 for high-detail or scaled artwork.',
    warnings: ['Low precision can introduce visible stair-stepping or alignment changes in detailed SVGs.']
  },
  {
    id: 'color.blur',
    path: 'color.blur',
    section: 'vectorization',
    group: 'Advanced Layer Controls',
    label: 'Color blur',
    explanation: 'Blurs only the color layer before color tracing.',
    technicalEffect: 'Applies blur to color-layer source pixels without changing the lineart-layer blur.',
    defaultValue: pixels(defaultVectorOptions.color.blur),
    validValues: '0px to 4px',
    recommendedValues: 'Use 0.3-0.7px for watercolor grain and lower values for crisp flat colors.',
    warnings: ['High color blur can merge neighboring colors and lose small paint details.']
  },
  {
    id: 'color.underpaintStrokeWidth',
    path: 'color.underpaintStrokeWidth',
    section: 'vectorization',
    group: 'Advanced Layer Controls',
    label: 'Underpaint stroke',
    explanation: 'Adds a same-color stroke around color fills to overlap neighboring shapes.',
    technicalEffect: 'Color paths are emitted with a stroke matching their fill at this width.',
    defaultValue: pixels(defaultVectorOptions.color.underpaintStrokeWidth),
    validValues: '0px to 6px',
    recommendedValues: 'Use 0.25-0.75px to hide white gaps in layered watercolor. Use 0 for exact fills.',
    warnings: ['Large underpaint strokes can muddy edges or cover fine lineart when layers overlap.']
  },
  {
    id: 'color.trace.minArea',
    path: 'color.trace.minArea',
    section: 'vectorization',
    group: 'Advanced Layer Controls',
    label: 'Color trace min area',
    explanation: 'Removes tiny islands from the color layer only.',
    technicalEffect: 'Overrides the shared contour minimum area for color-layer paths.',
    defaultValue: `${defaultVectorOptions.color.trace.minArea}px2`,
    validValues: '0px2 to 500px2',
    recommendedValues: 'Use 3-8 for detailed watercolor and 12+ for lighter SVGs.',
    warnings: ['High values remove small color accents and texture.']
  },
  {
    id: 'color.trace.simplify',
    path: 'color.trace.simplify',
    section: 'vectorization',
    group: 'Advanced Layer Controls',
    label: 'Color trace simplify',
    explanation: 'Simplifies color-layer contours only.',
    technicalEffect: 'Overrides the shared RDP simplification value for color-layer paths.',
    defaultValue: pixels(defaultVectorOptions.color.trace.simplify),
    validValues: '0px to 8px',
    recommendedValues: 'Use 0.35-0.8 for watercolor detail and 1+ for lighter files.',
    warnings: ['High values can make color shapes no longer line up with lineart.']
  },
  {
    id: 'color.trace.smooth',
    path: 'color.trace.smooth',
    section: 'vectorization',
    group: 'Advanced Layer Controls',
    label: 'Color trace smooth',
    explanation: 'Smooths color-layer contours only.',
    technicalEffect: 'Overrides the shared curve smoothing value for color-layer paths.',
    defaultValue: percent(defaultVectorOptions.color.trace.smooth),
    validValues: '0% to 100%',
    recommendedValues: 'Use 10-60% for soft washes and lower values for hard-edged graphics.',
    warnings: ['High smoothing can shift edges and soften intended texture.']
  },
  {
    id: 'binary.blur',
    path: 'line.blur',
    section: 'vectorization',
    group: 'Advanced Layer Controls',
    label: 'Lineart blur',
    explanation: 'Blurs only the lineart layer before thresholding.',
    technicalEffect: 'Applies blur to lineart source pixels without changing the color-layer blur.',
    defaultValue: pixels(defaultVectorOptions.binary.blur),
    validValues: '0px to 4px',
    recommendedValues: 'Use 0-0.15px for crisp ink and 0.2-0.5px to soften noisy scans.',
    warnings: ['Too much lineart blur can merge nearby strokes or erase fine hatching.']
  },
  {
    id: 'binary.strokeWidth',
    path: 'line.strokeWidth',
    section: 'vectorization',
    group: 'Advanced Layer Controls',
    label: 'Lineart stroke',
    explanation: 'Adds an SVG stroke around generated lineart paths.',
    technicalEffect: 'Lineart paths are emitted with a stroke matching the line color at this width.',
    defaultValue: pixels(defaultVectorOptions.binary.strokeWidth),
    validValues: '0px to 8px',
    recommendedValues: 'Use 0-0.3px for subtle reinforcement and 0.4-0.8px for bolder ink.',
    warnings: ['Large strokes can close holes, thicken lettering, and cover color detail.']
  },
  {
    id: 'binary.trace.minArea',
    path: 'line.trace.minArea',
    section: 'vectorization',
    group: 'Advanced Layer Controls',
    label: 'Lineart trace min area',
    explanation: 'Removes tiny islands from the lineart layer only.',
    technicalEffect: 'Overrides the shared contour minimum area for lineart paths.',
    defaultValue: `${defaultVectorOptions.binary.trace.minArea}px2`,
    validValues: '0px2 to 500px2',
    recommendedValues: 'Use 2-5 for detailed ink and 8+ to remove dust.',
    warnings: ['High values can delete dots, texture, small punctuation, and broken line ends.']
  },
  {
    id: 'binary.trace.simplify',
    path: 'line.trace.simplify',
    section: 'vectorization',
    group: 'Advanced Layer Controls',
    label: 'Lineart trace simplify',
    explanation: 'Simplifies lineart contours only.',
    technicalEffect: 'Overrides the shared RDP simplification value for lineart paths.',
    defaultValue: pixels(defaultVectorOptions.binary.trace.simplify),
    validValues: '0px to 8px',
    recommendedValues: 'Use 0.2-0.45 for detailed lineart and 0.6-1.2 for cleaner, smaller output.',
    warnings: ['High values can deform lettering, hatching, and expressive ink edges.']
  },
  {
    id: 'binary.trace.smooth',
    path: 'line.trace.smooth',
    section: 'vectorization',
    group: 'Advanced Layer Controls',
    label: 'Lineart trace smooth',
    explanation: 'Smooths lineart contours only.',
    technicalEffect: 'Overrides the shared curve smoothing value for lineart paths.',
    defaultValue: percent(defaultVectorOptions.binary.trace.smooth),
    validValues: '0% to 100%',
    recommendedValues: 'Use 6-18% for ink, lower for mechanical art, and higher only for intentionally soft outlines.',
    warnings: ['Too much smoothing can erase hand-drawn character or close small negative spaces.']
  },
  {
    id: 'output.addBackground',
    path: 'output.addBackground',
    section: 'vectorization',
    group: 'Output',
    label: 'Add real background rectangle',
    explanation: 'Adds an actual SVG rectangle behind the traced artwork.',
    technicalEffect: 'The exported SVG includes a full-size background rect filled with the Background color.',
    defaultValue: bool(defaultVectorOptions.output.addBackground),
    validValues: 'On or off',
    recommendedValues: 'Turn on when you need a solid background in SVG viewers or PNG export. Leave off for transparent SVG artwork.',
    warnings: ['A real background rectangle removes transparency unless deleted later.']
  },
  {
    id: 'output.backgroundColor',
    path: 'output.backgroundColor',
    section: 'vectorization',
    group: 'Output',
    label: 'Background color',
    explanation: 'Sets the color of the optional real background rectangle.',
    technicalEffect: 'When Add real background rectangle is on, this hex color is used as the rectangle fill.',
    defaultValue: color(defaultVectorOptions.output.backgroundColor),
    validValues: 'Any color available from the browser color picker, stored as hex.',
    recommendedValues: 'Use white for paper-like output, transparent SVG with the rectangle off for overlays, or a brand color for finished assets.',
    warnings: ['This does nothing unless Add real background rectangle is enabled.']
  },
  {
    id: 'vector.vectorize',
    path: 'vectorization.vectorize',
    section: 'vectorization',
    group: 'Output',
    label: 'Vectorize',
    explanation: 'Runs vectorization with the current settings.',
    technicalEffect: 'Calls the vectorization engine with the loaded source image and current VectorOptions, then stores the SVG result and stats.',
    defaultValue: 'Action; disabled until a source image is loaded',
    validValues: 'Button action',
    recommendedValues: 'Use after changing several settings when Live preview is off.',
    warnings: ['High-detail settings can take longer and may temporarily make the UI busy.']
  },
  {
    id: 'vector.sendToEditor',
    path: 'vectorization.sendToEditor',
    section: 'vectorization',
    group: 'Output',
    label: 'Send to Editing',
    explanation: 'Copies the current vectorization result into the Editing tab.',
    technicalEffect: 'Stores the generated SVG in editor state and switches the active tab to Editing.',
    defaultValue: 'Action; disabled until a vector result exists',
    validValues: 'Button action',
    recommendedValues: 'Use after vectorization when you want palette, stroke, color, or export adjustments.',
    warnings: ['Sending a new result replaces the SVG currently loaded in Editing.']
  },
  {
    id: 'vector.exportSvg',
    path: 'vectorization.exportSvg',
    section: 'vectorization',
    group: 'Output',
    label: 'Export SVG',
    explanation: 'Downloads the current vectorization result as SVG.',
    technicalEffect: 'Serializes the generated SVG string and downloads it using the source file name when available.',
    defaultValue: 'Action; disabled until SVG output exists',
    validValues: 'Button action',
    recommendedValues: 'Use for scalable vector output and further editing in design tools.',
    warnings: ['SVGs with many colors, low simplification, or high Max side can be large.']
  },
  {
    id: 'vector.exportPng',
    path: 'vectorization.exportPng',
    section: 'vectorization',
    group: 'Output',
    label: 'Export PNG',
    explanation: 'Downloads a raster PNG of the current vectorization result.',
    technicalEffect: 'Rasterizes the generated SVG in the browser and downloads a 2x PNG.',
    defaultValue: 'Action; disabled until SVG output exists',
    validValues: 'Button action',
    recommendedValues: 'Use for previews, raster uploads, or checking how the SVG renders outside the app.',
    warnings: ['PNG output is not path-editable and large SVGs can take longer to rasterize.']
  }
];

export const optionHelpById = Object.fromEntries(optionHelp.map((item) => [item.id, item])) as Record<string, OptionHelp>;

export const helpRecipes: HelpRecipe[] = [
  {
    title: 'Watercolor with ink',
    goal: 'Keep soft color washes while preserving dark outlines.',
    settings: ['Mode: layered', 'Background method: edge-connected', 'Quantizer: OKLab k-means++', 'Colors: 24-64', 'Ink chroma guard: 50-90', 'Color blur: 0.3-0.7px', 'Lineart blur: 0.05-0.2px'],
    watchFor: 'If dark paint becomes ink, lower Lineart darkness or Ink chroma guard. If white gaps appear, add a small Underpaint stroke or turn off Exclude lineart from color layer.'
  },
  {
    title: 'Clean black lineart',
    goal: 'Produce crisp monochrome paths from ink, pencil, or lettering.',
    settings: ['Mode: binary', 'Max side: 1800-2800px', 'Pre-blur: 0-0.15px', 'Threshold mode: manual or Otsu', 'Threshold: 160-190', 'Line color: near black', 'Lineart trace simplify: 0.2-0.5'],
    watchFor: 'If paper texture appears, raise Contour minimum area, add a little Lineart blur, or lower the Threshold.'
  },
  {
    title: 'Lightweight SVG',
    goal: 'Keep output small enough for web use and quick editing.',
    settings: ['Mode: color or binary', 'Max side: 900-1500px', 'Colors: 8-18', 'Contour minimum area: 10-25px2', 'RDP simplification: 1-2px', 'Precision: 0-1'],
    watchFor: 'Small files come from fewer paths and fewer coordinates; expect some loss of tiny texture and subtle color transitions.'
  },
  {
    title: 'Preserving detail',
    goal: 'Favor fidelity over speed and file size.',
    settings: ['Max side: 2400-3200px', 'Colors: 48-96', 'Iterations: 30-45', 'Max samples: 250,000-500,000', 'Contour minimum area: 0-4px2', 'RDP simplification: 0.2-0.5px', 'Precision: 2-4'],
    watchFor: 'Large settings can create very heavy SVGs. Export PNG first if you only need a raster deliverable.'
  },
  {
    title: 'Removing paper background',
    goal: 'Remove scan paper while keeping pale artwork.',
    settings: ['Remove paper/background: on', 'Background method: edge-connected', 'Paper tolerance: 6-14%', 'Min paper lightness: 72-84%', 'Sample inset: 10-28px', 'Preview foreground mask: on while tuning'],
    watchFor: 'If pale art disappears, lower Paper tolerance or raise Min paper lightness. If border shadows remain, increase Sample inset.'
  },
  {
    title: 'Avoiding white gaps',
    goal: 'Make adjacent color and ink layers overlap slightly.',
    settings: ['Underpaint stroke: 0.25-0.75px', 'Exclude lineart from color layer: off when needed', 'Color trace simplify: keep lower than 1px', 'Lineart stroke: 0.1-0.4px'],
    watchFor: 'Too much overlap can muddy edges. Increase in small steps and inspect at 100% zoom.'
  },
  {
    title: 'Avoiding black blobs',
    goal: 'Prevent shadows or saturated paint from becoming ink.',
    settings: ['Lineart darkness: lower toward 130-150', 'Ink chroma guard: lower toward 50-80', 'Threshold: lower if using manual', 'Sauvola k: lower if adaptive thresholding grabs texture'],
    watchFor: 'If actual ink disappears too, increase the guard/threshold gradually or use Lineart stroke instead of reclassifying more pixels as ink.'
  }
];
